# Generated by Django 4.2.30 on 2026-06-11 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=500, unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('news', 'Yangiliklar'), ('announcement', "E'lonlar"), ('regulation', 'Qonunchilik'), ('report', 'Hisobotlar'), ('other', 'Boshqa')], default='news', max_length=50, verbose_name='Kategoriya')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='Holat')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/articles/', verbose_name='Muqova rasmi')),
                ('intro', models.TextField(blank=True, verbose_name='Qisqa mazmun')),
                ('body', models.TextField(verbose_name='Maqola matni')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tanlangan')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('subtitle', models.TextField(blank=True, verbose_name="Qo'shimcha matn")),
                ('image', models.ImageField(upload_to='images/banners/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ism Familiya')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Elektron pochta')),
                ('subject', models.CharField(max_length=300, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('done', 'Hal etildi')], default='new', max_length=20)),
                ('note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nazorat Qilish Inspeksiyasi', max_length=300)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/site/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('working_hours', models.CharField(blank=True, max_length=200)),
                ('telegram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('footer_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.menuitem', verbose_name='Ota-menyu')),
            ],
            options={
                'verbose_name': 'Menyu elementi',
                'verbose_name_plural': 'Menyu elementlari',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='files/', verbose_name='Fayl')),
                ('file_type', models.CharField(choices=[('image', 'Rasm'), ('document', 'Hujjat'), ('other', 'Boshqa')], default='image', max_length=20)),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Hajm (bayt)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fayl',
                'verbose_name_plural': 'Fayllar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/gallery/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='api.menuitem', verbose_name="Menyu bo'limi"),
        ),
    ]
