# Generated by Django 4.2.30 on 2026-06-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.TextField(blank=True, help_text='Asosiy sarlavha. Yangi qator uchun \\n, oltin rang uchun *matn* ishlating'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1',
            field=models.CharField(blank=True, default='14', max_length=50, verbose_name='Stat 1 qiymati'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat1_label',
            field=models.CharField(blank=True, default='Viloyat', max_length=100, verbose_name='Stat 1 yorliq'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2',
            field=models.CharField(blank=True, default='12000', max_length=50, verbose_name='Stat 2 qiymati'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat2_label',
            field=models.CharField(blank=True, default="Tekshirilgan ob'ekt", max_length=100, verbose_name='Stat 2 yorliq'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat3',
            field=models.CharField(blank=True, default='98', max_length=50, verbose_name='Stat 3 qiymati'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat3_label',
            field=models.CharField(blank=True, default='Hal etildi %', max_length=100, verbose_name='Stat 3 yorliq'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat4',
            field=models.CharField(blank=True, default='2011', max_length=50, verbose_name='Stat 4 qiymati'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat4_label',
            field=models.CharField(blank=True, default='Tashkil yil', max_length=100, verbose_name='Stat 4 yorliq'),
        ),
    ]
